name: "Podcast Generator Test by cwpearce"
author: "cwpearce"
description: "github sample from Ray Villalobos, by following a linkedin learn tutorial"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: "The committer's email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The committer's name"
    required: true
    default: ${{ github.actor }}
